### ISSUE TITLE
Not working connect

### ISSUE THREAD

**Issue by ghost** [forestryio/novela-hugo-starter#1]
Not working from https://forestry.io/starters/ but work from https://app.forestry.io/quick-start?repo=forestryio/novela-hugo-starter&engine=hugo&version=0.60.1

![Screenshot 2019-12-29 at 13 26 24](https://user-images.githubusercontent.com/2323952/71556929-df3edf80-2a3e-11ea-9c84-a789f0aab07c.png)

**Comment by DirtyF** [comment]
This is fixed, thanks for reporting. 🙏
