### ISSUE TITLE
Deploy failed in netlify

### ISSUE THREAD

**Issue by YutingBoom** [forestryio/novela-hugo-starter#5]
Hi, I love novela, elegant and simple. Thanks for your work.
But I came across a problem. When I choose Github as repository, and set hugo --gc --minify and public,(Step 1-3), HUGO_VERSION is right, but the netlify says 'Deploy failed'. I am a designer, so I don't know much about those. You list 5 steps, but I find that Step3 is same as Step 5. Would you give me some advice about how to solve this problem?

**Comment by DirtyF** [comment]
What Hugo version are you using?

The theme has a `netlify.toml` file which tells Netlify to use a Hugo version > 0.55.

I just updated the theme and it's working with current Hugo version (0.68.3):

https://hugo-novela-forestry.netlify.com/

I fixed the docs, thanks for reporting.

**Comment by YutingBoom** [comment]
Hugo Static Site Generator v0.68.3/extended darwin/amd64 BuildDate: unknown

**Comment by YutingBoom** [comment]
> What Hugo version are you using?

Hugo Static Site Generator v0.68.3/extended darwin/amd64 BuildDate: unknown
